CREATE SEQUENCE SEQ_COLETA
    START WITH 1
    INCREMENT BY 1 NOCACHE
  NOCYCLE;

CREATE TABLE TB_COLETA
(
    COLETA_ID           INTEGER DEFAULT SEQ_COLETA.NEXTVAL      NOT NULL,
    DATA_COLETA         VARCHAR(100)                            NOT NULL,
    ADRESS              VARCHAR(200)                            NOT NULL,
    TYPE_OF_RESIDUE     VARCHAR(100)                            NOT NULL
);


CREATE SEQUENCE SEQ_USERS
    START WITH 1
    INCREMENT BY 1 NOCACHE
 NOCYCLE;

CREATE TABLE TB_USERS
(
    USER_ID     INTEGER DEFAULT SEQ_USERS.NEXTVAL NOT NULL,
    EMAIL       VARCHAR2(100) NOT NULL,
    PASSWORD    VARCHAR2(100) NOT NULL,
    ACCOUNT_NON_EXPIRED NUMBER(1,0) NOT NULL,
    ACCOUNT_NON_LOCKED  NUMBER(1,0)  NOT NULL,
    CREDENTIALS_NON_EXPIRED NUMBER(1,0) NOT NULL,
    ENABLED     NUMBER(1,0)  NOT NULL,
    "ROLE"      VARCHAR2(100) DEFAULT USER NULL,
    CONSTRAINT TB_USERS_PK PRIMARY KEY (USER_ID),
    CONSTRAINT TB_USERS_UNIQUE UNIQUE (EMAIL)
)